version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: pokemon_api:${POKEMON_API_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      POKEMON_API_HOST: 0.0.0.0
      POKEMON_API_DB_HOST: pokemon_api-db
      POKEMON_API_DB_PORT: 5432
      POKEMON_API_DB_USER: pokemon_api
      POKEMON_API_DB_PASS: pokemon_api
      POKEMON_API_DB_BASE: pokemon_api

  db:
    image: postgres:13.8-bullseye
    hostname: pokemon_api-db
    environment:
      POSTGRES_PASSWORD: "pokemon_api"
      POSTGRES_USER: "pokemon_api"
      POSTGRES_DB: "pokemon_api"
    volumes:
    - pokemon_api-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U pokemon_api
      interval: 2s
      timeout: 3s
      retries: 40



volumes:
  pokemon_api-db-data:
    name: pokemon_api-db-data
